export const jobs = [
    {
        id: "j1",
        title: "SDE Intern",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "REST APIs"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://razorpay.com/jobs/sde-intern",
        description: "Looking for proactive SDE interns to help build the next generation of payment experiences. You will work closely with senior engineers on high-scale systems. Strong problem-solving skills and a passion for clean code are required."
    },
    {
        id: "j2",
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Communication"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "3–4.5 LPA",
        applyUrl: "https://www.tcs.com/careers",
        description: "Join our TCS Ignite program as a Graduate Engineer Trainee. You will undergo extensive training on enterprise technologies and work on global client projects. We value continuous learning and adaptability."
    },
    {
        id: "j3",
        title: "Junior Backend Developer",
        company: "Zomato",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Node.js", "MongoDB", "Redis"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "8–12 LPA",
        applyUrl: "https://zomato.com/careers/backend",
        description: "We are looking for a Junior Backend Developer to join our core food delivery engineering team. You will be responsible for building robust APIs and scaling our underlying infrastructure to handle millions of requests."
    },
    {
        id: "j4",
        title: "Frontend Intern",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["HTML", "CSS", "React Native"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://flipkart.com/careers",
        description: "Flipkart's Frontend Intern program offers a high-impact environment where you'll build features seen by millions. You should have a strong grasp of design principles and modern CSS frameworks. High ownership is expected."
    },
    {
        id: "j5",
        title: "QA Intern",
        company: "Infosys",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Selenium", "Manual Testing", "Jira"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "2.5–3.5 LPA",
        applyUrl: "https://infosys.com/careers",
        description: "The QA Intern will assist our quality assurance team in executing test cases and identifying software defects. This is a great opportunity to learn automated testing frameworks and industry-standard QA processes."
    },
    {
        id: "j6",
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bengaluru",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "Pandas", "Tableau"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://swiggy.com/careers",
        description: "Join Swiggy as a Data Analyst Intern and help us derive insights from vast amounts of delivery data. You will build dashboards, perform exploratory data analysis, and support decision-making across product teams."
    },
    {
        id: "j7",
        title: "Java Developer (0-1)",
        company: "Accenture",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Spring Boot", "Hibernate", "MS SQL"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "6–9 LPA",
        applyUrl: "https://accenture.com/careers",
        description: "Seeking a motivated Java Developer with 0-1 years of experience in Spring Boot application development. You will contribute to enterprise-level software solutions and participate in the full software development lifecycle."
    },
    {
        id: "j8",
        title: "Python Developer (Fresher)",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Django", "Functional Programming"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "10–15 LPA",
        applyUrl: "https://juspay.io/careers",
        description: "At Juspay, we build world-class payment infrastructure. As a Fresher Python Developer, you will work on highly concurrency systems and learn the art of functional programming at scale. Strong mathematical foundation required."
    },
    {
        id: "j9",
        title: "React Developer (1-3)",
        company: "Razorpay",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–25 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Seeking an experienced React Developer to lead the development of our merchant dashboard. You should have a deep understanding of state management, component architecture, and performance optimization in large-scale apps."
    },
    {
        id: "j10",
        title: "Android Developer Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Kotlin", "Android SDK", "MVVM"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "₹15k–₹30k/month Internship",
        applyUrl: "https://paytm.com/careers",
        description: "Join Paytm's mobile engineering team as an intern. You will assist in developing and maintaining features for the flagship Paytm app. Experience with Kotlin and a passion for mobile development are key."
    },
    {
        id: "j11",
        title: "Systems Engineer (0-1)",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Linux", "Python", "Networking"],
        source: "LinkedIn",
        postedDaysAgo: 8,
        salaryRange: "4–6 LPA",
        applyUrl: "https://cognizant.com/careers",
        description: "Junior Systems Engineer to support our cloud infrastructure projects. You will be responsible for system monitoring, basic troubleshooting, and automating routine tasks using Python and shell scripting."
    },
    {
        id: "j12",
        title: "Product Designer Intern",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Figma", "UI/UX", "Prototyping"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "₹40k–₹60k/month Internship",
        applyUrl: "https://cred.club/careers",
        description: "CRED is looking for a Product Designer Intern with an obsession for detail and premium aesthetics. You will work on user-centric designs for credit-worthy individuals, focusing on simplicity and luxury."
    },
    {
        id: "j13",
        title: "Backend Engineer (1-3)",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Ruby on Rails", "PostgreSQL", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "12–20 LPA",
        applyUrl: "https://freshworks.com/careers",
        description: "Join the Freshworks engineering team to build scalable CRM and support software. You should have strong experience in Ruby on Rails and a solid understanding of relational database design and cloud architecture."
    },
    {
        id: "j14",
        title: "Cloud Consultant (Fresher)",
        company: "IBM",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Cloud Computing", "Kubernetes", "DevOps"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "7–10 LPA",
        applyUrl: "https://ibm.com/careers",
        description: "Start your career as a Cloud Consultant at IBM. You will help clients navigate their digital transformations by implementing hybrid cloud solutions. Training on IBM Cloud and OpenShift will be provided."
    },
    {
        id: "j15",
        title: "Full Stack Developer (1-3)",
        company: "Zoho",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Java", "JavaScript", "React"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "8–15 LPA",
        applyUrl: "https://zoho.com/careers",
        description: "Zoho is looking for Full Stack Developers to build our suite of business productivity tools. You will have high autonomy and work in a culture that values long-term craftsmanship and product ownership."
    },
    {
        id: "j16",
        title: "Machine Learning Intern",
        company: "PhonePe",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://phonepe.com/careers",
        description: "Join the PhonePe ML team as an intern. You will help build models for fraud detection, recommendation engines, and user behavior analysis in a fast-paced fintech environment."
    },
    {
        id: "j17",
        title: "Associate Project Manager",
        company: "Capgemini",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Agile", "Excel", "Project Management"],
        source: "Naukri",
        postedDaysAgo: 10,
        salaryRange: "5–8 LPA",
        applyUrl: "https://capgemini.com/careers",
        description: "Junior project management role focused on coordinating cross-functional teams and ensuring on-time delivery of enterprise projects. You'll gain exposure to global business processes and Agile methodologies."
    },
    {
        id: "j18",
        title: "Content Designer (Fresher)",
        company: "Swiggy",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Copywriting", "Creative Thinking", "Social Media"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "4–6 LPA",
        applyUrl: "https://swiggy.com/careers",
        description: "Looking for a creative mind to join the Swiggy content team. You will write engaging copy for the app, marketing campaigns, and social media, ensuring our brand voice remains witty and relevant."
    },
    {
        id: "j19",
        title: "DevOps Engineer (1-3)",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Docker", "Terraform", "Jenkins"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "14–22 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Help us maintain 99.99% uptime for payment systems. You should have 1-3 years of experience in infrastructure as code, CI/CD pipelines, and managing production workloads on AWS or GCP."
    },
    {
        id: "j20",
        title: "Security Engineer (0-1)",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Penetration Testing", "OAuth", "API Security"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "12–18 LPA",
        applyUrl: "https://juspay.io/careers",
        description: "Join our security-first engineering team. You will be responsible for identifying vulnerabilities, conducting security audits, and implementing robust encryption and authentication mechanisms in our payment journeys."
    },
    {
        id: "j21",
        title: "Customer Success Associate",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Communication", "Relationship Management", "Product Knowledge"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "4–7 LPA",
        applyUrl: "https://freshworks.com/careers",
        description: "Manage relationships with our global enterprise clients. You will ensure successful product adoption, handle renewals, and act as the voice of the customer within the product organization."
    },
    {
        id: "j22",
        title: "Data Scientist (1-3)",
        company: "Oracle",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "SQL", "Scikit-Learn"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–28 LPA",
        applyUrl: "https://oracle.com/careers",
        description: "Oracle is looking for a Data Scientist to work on our cloud database optimization engine. You should have a strong background in statistics, machine learning, and data mining techniques."
    },
    {
        id: "j23",
        title: "Software Engineer - C++",
        company: "SAP",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C++", "OOD", "Multithreading"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "12–20 LPA",
        applyUrl: "https://sap.com/careers",
        description: "Core engineering role at SAP. You will work on building high-performance kernels for enterprise resource planning systems. Experience with multithreading and memory management in C++ is essential."
    },
    {
        id: "j24",
        title: "Technical Writer Intern",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Technical Writing", "DITA", "Documentation"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://salesforce.com/careers",
        description: "Support our documentation team by creating and updating API guides, user manuals, and help articles. You should have a clear writing style and the ability to translate complex concepts for end-users."
    },
    {
        id: "j25",
        title: "iOS Developer (0-1)",
        company: "Swiggy",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Swift", "UIKit", "Combine"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10–15 LPA",
        applyUrl: "https://swiggy.com/careers",
        description: "Join the Swiggy iOS application team. You will build high-quality user experiences for our diners and delivery partners. Deep understanding of the iOS platform and Swift language is required."
    },
    {
        id: "j26",
        title: "Business Analyst (Fresher)",
        company: "Wipro",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Analysis", "Communication", "Documentation"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "3.5–5.5 LPA",
        applyUrl: "https://wipro.com/careers",
        description: "Wipro is looking for recent graduates to join our business analysis track. You will work with clients to gather requirements, document business processes, and support technical teams during implementation phases."
    },
    {
        id: "j27",
        title: "Cybersecurity Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Networking", "Ethical Hacking", "SOC"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹18k–₹30k/month Internship",
        applyUrl: "https://paytm.com/careers",
        description: "Learn the ropes of cybersecurity in a high-stakes fintech environment. You will assist in monitoring security alerts, performing basic vulnerability scans, and supporting incident response activities."
    },
    {
        id: "j28",
        title: "Site Reliability Engineer",
        company: "Amazon",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Cloud Infrastructure", "Kubernetes"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–35 LPA",
        applyUrl: "https://amazon.jobs",
        description: "Ensure the reliability and performance of Amazon's massive cloud services. You will combine software engineering and systems administration to build highly available automated systems."
    },
    {
        id: "j29",
        title: "Node.js Developer (0-1)",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Node.js", "Redis", "Kafka"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "15–22 LPA",
        applyUrl: "https://cred.club/careers",
        description: "Build low-latency microservices for the CRED platform. We value extreme engineering quality and a deep understanding of distributed systems and event-driven architectures."
    },
    {
        id: "j30",
        title: "UI Designer (Fresher)",
        company: "Zomato",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Figma", "Visual Design", "Typography"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "6–9 LPA",
        applyUrl: "https://zomato.com/careers",
        description: "Zomato is looking for fresh design talent to work on our visual design language. You will assist in creating assets for marketing campaigns and refining UI components across our mobile and web apps."
    },
    {
        id: "j31",
        title: "React Native Developer",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Remote",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Mobile Design"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "16–28 LPA",
        applyUrl: "https://flipkart.com/careers",
        description: "Build cross-platform mobile experiences for the largest e-commerce platform in India. You should have a solid portfolio of mobile apps and a deep understanding of React Native performance tuning."
    },
    {
        id: "j32",
        title: "Database Admin Intern",
        company: "Oracle",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["SQL", "Database Design", "Performance Tuning"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://oracle.com/careers",
        description: "Join Oracle's database operations team as an intern. You will learn the industry-standard database management software and assist in day-to-day administration tasks for internal systems."
    },
    {
        id: "j33",
        title: "SDE-1 (Back-end)",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Golang", "MySQL", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–26 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Core engineering role at Razorpay. You will work on building scalable and secure payment gateways and APIs using Golang. High ownership and a passion for fintech are required."
    },
    {
        id: "j34",
        title: "ML Ops Engineer",
        company: "PhonePe",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kubeflow", "Python", "Docker"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18–30 LPA",
        applyUrl: "https://phonepe.com/careers",
        description: "Bridge the gap between data science and production systems. You will be responsible for building and maintaining automated ML pipelines and ensuring smooth deployment of models at scale."
    },
    {
        id: "j35",
        title: "Graphic Designer Intern",
        company: "Zomato",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Photoshop", "Illustrator", "Branding"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://zomato.com/careers",
        description: "Zomato's brand team is looking for a graphic design intern with a flair for creative storytelling. You will assist in creating marketing visuals, social media content, and branding collateral."
    },
    {
        id: "j36",
        title: "Test Engineer (0-1)",
        company: "TCS",
        location: "Bhubaneswar",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Automation Testing", "PyTest", "API Testing"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.tcs.com/careers",
        description: "Join our banking and financial services unit as a Test Engineer. You will work on automated testing for large-scale banking applications, ensuring reliability and security of transactions."
    },
    {
        id: "j37",
        title: "Digital Marketing Intern",
        company: "Uber",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SEO", "SEM", "Content Strategy"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹25k–₹45k/month Internship",
        applyUrl: "https://uber.com/careers",
        description: "Uber is looking for a digital marketing enthusiast to join our India team. You will support our growth marketing initiatives across search, social, and app marketing channels."
    },
    {
        id: "j38",
        title: "Frontend Engineer (1-3)",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "PureScript", "Canvas"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–25 LPA",
        applyUrl: "https://juspay.io/careers",
        description: "Work on highly-functional and beautiful UI components at Juspay. We use PureScript/Haskell for building reliable frontend architectures. This is for engineers who value type-safety and performance."
    },
    {
        id: "j39",
        title: "HR Coordinator (Fresher)",
        company: "Accenture",
        location: "Multiple Cities",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Communication", "Organization", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "3–5 LPA",
        applyUrl: "https://accenture.com/careers",
        description: "Start your HR career at Accenture. You will assist our recruitment team in coordinating interviews, onboarding candidates, and managing employee engagement activities across our India operations."
    },
    {
        id: "j40",
        title: "Product Analyst Intern",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["SQL", "Growth Hacking", "Product Strategy"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://razorpay.com/jobs",
        description: "Use your analytical skills to drive product growth at Razorpay. You will work on user journey optimization, conversion rate tracking, and defining product roadmaps based on data insights."
    },
    {
        id: "j41",
        title: "Application Support Engineer",
        company: "Cognizant",
        location: "Kolkata",
        mode: "Onsite",
        experience: "0-1",
        skills: ["SQL", "LinuxTroubleshooting", "Support"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "3.5–5 LPA",
        applyUrl: "https://cognizant.com/careers",
        description: "Join our managed services team to support enterprise applications for global clients. You will be responsible for incident resolution, system monitoring, and basic maintenance tasks."
    },
    {
        id: "j42",
        title: "UX Researcher Intern",
        company: "CRED",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["User Interviews", "Surveys", "Empathy"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://cred.club/careers",
        description: "CRED's design research team is looking for a curious intern to help us understand consumer behavior. You will assist in qualitative research, usability testing, and synthesis of user insights."
    },
    {
        id: "j43",
        title: "Full Stack Intern",
        company: "Swiggy",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "Go", "Postgres"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://swiggy.com/careers",
        description: "Work across the stack to build and ship new features for the Swiggy ecosystem. This is a high-ownership intern role where you'll be treated as a full-time engineer from day one."
    },
    {
        id: "j44",
        title: "Cloud Support Engineer",
        company: "Amazon Web Services",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["AWS", "Linux", "Networking"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "14–24 LPA",
        applyUrl: "https://amazon.jobs",
        description: "Help AWS customers worldwide build high-scale cloud architectures. You will troubleshoot technical issues, advocate for service improvements, and develop tools to solve recurrent problems."
    },
    {
        id: "j45",
        title: "Sales Engagement Associate",
        company: "Freshworks",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Sales", "Communication", "Outreach"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "4.5–7 LPA",
        applyUrl: "https://freshworks.com/careers",
        description: "Join the Freshworks sales development team and help identify new business opportunities globally. You should have a dynamic personality and excellent verbal/written communication skills."
    },
    {
        id: "j46",
        title: "Data Operations Intern",
        company: "NielsenIQ",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Excel", "Data Validation"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://nielseniq.com/careers",
        description: "Support our data operations team in ensuring the accuracy and integrity of our global retail data. You will work on data cleansing, validation, and regular reporting tasks."
    },
    {
        id: "j47",
        title: "Go Developer (1-3)",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Go", "Distributed Systems", "gRPC"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18–28 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "We are scaling our core payment platforms using Go. We are looking for engineers with experience in building concurrent systems and a deep interest in performance tuning and system design."
    },
    {
        id: "j48",
        title: "Customer Support Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Empathy", "Communication", "Conflict Resolution"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "₹12k–₹20k/month Internship",
        applyUrl: "https://paytm.com/careers",
        description: "Provide world-class support to Paytm users. You will handle customer queries, resolve complaints, and assist in maintaining the high customer satisfaction ratings of our platform."
    },
    {
        id: "j49",
        title: "Content Marketing Associate",
        company: "Zomato",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Writing", "Social Media Trends", "SEO"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "5–8 LPA",
        applyUrl: "https://zomato.com/careers",
        description: "Zomato is looking for a creative writer to join the content marketing team. You will create blog posts, social media captions, and in-app content that resonates with our foodie community."
    },
    {
        id: "j50",
        title: "Backend Engineer (0-1)",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "C++", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "12–18 LPA",
        applyUrl: "https://juspay.io/careers",
        description: "At Juspay, you will work on the core engineering problems of the fintech industry. We are looking for people with strong algorithmic thinking and a deep passion for software development at its lowest levels."
    },
    {
        id: "j51",
        title: "UI Engineer Intern",
        company: "Zoho",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["HTML", "CSS", "Vanilla JS"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://zoho.com/careers",
        description: "Learn the art of building scalable and performant UI components using vanilla JS at Zoho. You will work with a team of expert engineers who value craftsmanship and simple, robust solutions."
    },
    {
        id: "j52",
        title: "Cloud Ops Intern",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Azure", "Scripting", "SysAdmin"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k–₹60k/month Internship",
        applyUrl: "https://microsoft.com/careers",
        description: "Join the Azure operations team as an intern. You will learn how to manage and scale cloud resources efficiently and support infrastructure reliability for millions of global users."
    },
    {
        id: "j53",
        title: "Data Analyst (1-3)",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "SQL", "Statistic Modeling"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "https://flipkart.com/careers",
        description: "Analyze vast amount of customer data to drive growth and product improvements at Flipkart. You should have a solid foundation in statistics and strong technical skills in SQL and Python."
    },
    {
        id: "j54",
        title: "Research Scientist Intern",
        company: "IBM Research",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["AI", "Research", "Math"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "₹40k–₹70k/month Internship",
        applyUrl: "https://ibm.com/careers",
        description: "IBM Research India is looking for a research intern to work on cutting-edge AI and quantum computing topics. You must have a strong academic record and a passion for scientific discovery."
    },
    {
        id: "j55",
        title: "UX Designer (1-3)",
        company: "Zomato",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["UI/UX Design", "Wireframing", "User Centric Design"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–22 LPA",
        applyUrl: "https://zomato.com/careers",
        description: "Redesign the future of dining and food delivery at Zomato. You should be a problem-solver who can create simple and delightful user experiences across all Zomato products."
    },
    {
        id: "j56",
        title: "Site Reliability Intern",
        company: "Cisco",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Networking", "Linux", "Scripting"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹25k–₹45k/month Internship",
        applyUrl: "https://cisco.com/careers",
        description: "Learn how to build and maintain high-scale network infrastructure as an SRE intern at Cisco. You will gain experience with industry-standard monitoring and automation tools."
    },
    {
        id: "j57",
        title: "iOS Intern",
        company: "PhonePe",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Swift", "Mobile App Dev", "UIKIT"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹30k–₹55k/month Internship",
        applyUrl: "https://phonepe.com/careers",
        description: "Join the PhonePe mobile team as an iOS intern. You will help build out new consumer-facing features for the flagship PhonePe app using Swift and the latest Apple technologies."
    },
    {
        id: "j58",
        title: "Backend Engineer (1-3)",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Distributed Architecture", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–35 LPA",
        applyUrl: "https://cred.club/careers",
        description: "Work on the backbone of the CRED platform. We are looking for experienced backend engineers who thrive in a fast-paced environment and value high quality engineering over everything else."
    },
    {
        id: "j59",
        title: "Product Marketing Intern",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Content Creation", "Market Research", "Creativity"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://freshworks.com/careers",
        description: "Support our product marketing team in Chennai. You will help with market research, creating sales collateral, and coordinating cross-functional product launches."
    },
    {
        id: "j60",
        title: "Java Full Stack (0-1)",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Angular", "Spring"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "4–7 LPA",
        applyUrl: "https://tcs.com/careers",
        description: "Join our digital transformation team as a Java Full Stack Developer. You will work on building end-to-end web applications for our global clients using modern web technologies."
    }
];
